// <auto-generated />
using JanusFsnBack;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JanusFsnBack.Migrations
{
    [DbContext(typeof(JanusDbContext))]
    [Migration("20230809144337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("JanusFsnBack.Entites.AdSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slot1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.ToTable("AdSlots");
                });

            modelBuilder.Entity("JanusFsnBack.Entites.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("JanusFsnBack.Entites.AdSlot", b =>
                {
                    b.HasOne("JanusFsnBack.Entites.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });
#pragma warning restore 612, 618
        }
    }
}
